vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - github.copilot
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
tasks:
  - init: npm install
  - command: npm run dev
    name: dev-server
ports:
  - port: 3000
    onOpen: open-browser
    name: server
